spring.application.name=leprechaun-invest
spring.datasource.url=jdbc:mysql://localhost/leprechauninvest
spring.datasource.username=${usuario}
spring.datasource.password=${senhaDoBanco}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SMTP_USERNAME:danielmgdfpm@gmail.com}
spring.mail.password=${SMTP_PASSWORD:sphdpftrdcaqhgbn}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true